meta_product_name: "La Mif"
meta_title: "La Mif - Les kids ont le Père-Noël, les grands ont la Mif !"
meta_description: "Inscrivez les membres de votre famille sur la Mif et partagez ensemble vos idées de cadeaux !"
meta_image: "xmas_home_cropped.jpg" # should exist in `app/assets/images/`
meta_type: "Website"
meta_url: "http://lamif.club"
